export const personalInfo = {
    name: "Gautham Ram U M",
    role: "AI/ML, Web dev & Andriod APP dev and Web3 Engineer",
    location: "Bangalore, India",
    university: "Alliance University (Kalvium), 2024–28",
    currently: "Building @ Digital South Trust",
    interests: "Building DeFi, AI, Decentralized Systems, Web2 Products, and Machine Learning",
    tagline: "AI/ML, Web dev & Andriod APP dev and Blockchain Engineer",
    bio: "I'm a AI/ML, Web dev & Andriod APP dev and Web3 Developer based in Bengaluru, India, with a deep passion for building decentralized applications, crafting engaging web experiences, and contributing to open-source. Specializing in modern JavaScript, Solidity smart contracts, and responsive, pixel-perfect CSS design, I focus on delivering seamless, user-centric interfaces. With a strong eye for detail and a commitment to efficient execution, I bring complex ideas to life by blending robust functionality with elegant design.",
    email: "gauthamram.um@gmail.com",
    phone: "+91 9342560109",
    linkedin: "https://linkedin.com/in/gautham-ram-4404b431a",
    github: "https://github.com/Umgauthamram",
    twitter: "https://x.com/GauthamRam1613",
};

export const workExperience = [
    {
        company: "Digital South Trust",
        role: "Blockchain/Web dev & Andriod APP dev Engineer & Project Manager",
        period: "Oct 2025 – Present",
        location: "Bengaluru, India (Remote)",
        points: [
            "Led Web3 initiatives as Project Manager, managing full lifecycle of blockchain solutions and smart contract deployments, mentoring a team of interns.",
            "Bridged Web2 architectures with Web3 ecosystems for seamless technology integration.",
            "Directed end-to-end delivery of decentralized applications, coordinating cross-functional teams.",
        ],
    },
    {
        company: "Self-Employed / Freelance",
        role: "Full-Stack, AI/ML & Web3 Developer",
        period: "Jun 2024 – Present",
        location: "Remote",
        points: [
            "Architected, built, and launched responsive web apps, intelligent AI/ML integrations, decentralized solutions (Web3), and Android applications for diverse global clients.",
            "Designed and implemented secure RESTful/GraphQL APIs, optimized database systems, and crafted smooth UI/UX micro-interactions.",
            "Collaborated directly with clients to translate business requirements into clean, production-ready codebases with modern design aesthetics.",
        ],
    },
];

export const projects = [
    {
        id: "saakshya",
        name: "Saakshya – Supply Chain Provenance",
        description: "Enterprise supply-chain tracking, asset provenance, and cryptographic verification platform anchoring physical journeys onto EVM blockchains (Polygon/Sepolia) using direct & high-throughput Merkle Tree batching.",
        tags: ["Next.js", "MongoDB", "Solidity", "EVM", "Merkle Trees", "BullMQ", "Redis"],
        github: "https://github.com/Umgauthamram/saakshya",
        live: null,
        filter: "Blockchain",
    },
    {
        id: "sandbench",
        name: "SandBench – Secure Benchmarking",
        description: "🏆 Winner of the Age of AGI Hackathon! A secure code benchmarking platform, AI model evaluation framework, and reinforcement learning environment for code repair.",
        tags: ["Next.js", "Python", "Docker", "Redis"],
        github: "https://github.com/Umgauthamram/sandbench.git",
        live: "https://sandbench.vercel.app/",
        filter: "AI/ML",
    },
    {
        id: "tohappen",
        name: "ToHappen – AI Task Organizer",
        description: "A premium AI-powered task organizer and workflow planner. Parses natural language plans via Gemini AI, structures scheduled checklists, organizes collapsible color-coded folders, and integrates a transactional bug & feedback desk.",
        tags: ["Next.js", "Tailwind CSS", "MongoDB", "Gemini API", "JWT", "NodeMailer"],
        github: "https://github.com/Umgauthamram/ToHappen",
        live: "https://tohappen.vercel.app/",
        filter: "AI",
    },
    {
        id: "devmind",
        name: "DevMind – AI Code Reviewer",
        description: "AI-powered IDE extension for automated code reviews, bug detection, and agentic prompt generation directly inside the developer's workspace.",
        tags: ["TypeScript", "IDE Extension", "Node.js", "AI Code Review"],
        github: "https://github.com/Umgauthamram/devmind",
        live: "https://marketplace.visualstudio.com/items?itemName=Gauthamram.AI-devmind",
        liveText: "IDE Extension",
        filter: "AI/ML",
    },
    {
        id: "multichange",
        name: "Multichange – AI Diagram Generator",
        description: "AI-powered web application that intelligently transforms unstructured text into high-definition diagrams (Mermaid, Flowcharts, Sequence). Includes smart layouts and syntax purity generation.",
        tags: ["Next.js", "Python", "Gemini 1.5", "Vercel", "Mermaid.js"],
        github: "https://github.com/Umgauthamram/MultiChange",
        live: "https://multi-change.vercel.app/",
        filter: "AI",
    },
    {
        id: "zenpark",
        name: "ZenPark – Urban Parking System",
        description: "Real-time smart parking orchestration system with live digital twins, reservations, spatial map SVGs, and live analytics using WebSockets.",
        tags: ["Next.js", "Node.js", "WebSockets", "Prisma", "AWS RDS"],
        github: "https://github.com/Umgauthamram/zenparking",
        live: "https://zenparking.vercel.app",
        filter: "Web dev & Andriod APP dev",
    },
    {
        id: "ecommerce-kadukal",
        name: "Ecommerce Kadukal",
        description: "Comprehensive E-commerce platform with dynamic cart management, secure Stripe/PayPal integrations, and a robust admin analytics dashboard.",
        tags: ["React", "Node.js", "Express", "MongoDB", "Stripe"],
        github: "https://github.com/Umgauthamram/ASAP_s70_Ecommerce_kadukal",
        live: null,
        filter: "Web dev & Andriod APP dev",
    },
    {
        id: "ballot",
        name: "Ballot – Immutable Voting",
        description: "Blockchain e-voting core for universities ensuring immutable ballot records, live results, and strict audit logs.",
        tags: ["Solidity", "React", "Hardhat", "MongoDB"],
        github: "https://github.com/Umgauthamram",
        live: "https://ballot-xi.vercel.app/",
        filter: "Blockchain",
    },
    {
        id: "krevelance",
        name: "Krevelance – Financial AI",
        description: "AI-driven financial analytics platform predicting revenue, profit/loss margins & churn out of raw document data.",
        tags: ["MERN", "Gemini 1.5", "FastAPI", "Pandas"],
        github: "https://github.com/kalviumcommunity/S70_Gauthamram_Capstone_krevelance",
        live: "https://krevelance.netlify.app/",
        filter: "AI",
    },
    {
        id: "weird-sound",
        name: "Weird Sound – Music Portal",
        description: "A sleek music listening web application featuring dynamic photo integration and remote asset storage.",
        tags: ["React", "Node.js", "Express", "Cloudinary"],
        github: "https://github.com/Umgauthamram/Weird-sound-",
        live: null,
        filter: "Web dev & Andriod APP dev",
    },
    {
        id: "cogniform",
        name: "CogniForm – Agentic AI Workflow",
        description: "Agentic AI that autonomously batches, prioritizes & auto-completes repetitive internal workplace surveys.",
        tags: ["Python", "IBM WatsonX", "Granite", "Agentic AI"],
        github: "https://github.com/Umgauthamram/cogniform1",
        live: null,
        filter: "AI",
    },
    {
        id: "secureid",
        name: "SecureID – Decentralized Identity",
        description: "NFT-based DID authentication system using decentralized IPFS storage instead of standard server sessions.",
        tags: ["MERN", "IPFS", "NFT Auth", "Solidity"],
        github: "https://github.com/Umgauthamram/SecureID",
        live: null,
        filter: "Blockchain",
    },
];

export const skills = [
    {
        category: "Languages",
        items: ["JavaScript", "TypeScript", "Python", "Solidity", "Rust", "SQL"],
    },
    {
        category: "Frontend",
        items: ["React.js", "Next.js", "React Native", "TailwindCSS", "Vite", "Framer Motion", "HTML5/CSS3"],
    },
    {
        category: "Backend",
        items: ["Node.js", "Express.js", "FastAPI", "Prisma ORM"],
    },
    {
        category: "Databases",
        items: ["MongoDB", "PostgreSQL", "MySQL", "Firebase", "Supabase", "Redis"],
    },
    {
        category: "Web3 & Blockchain",
        items: [
            "Solidity", "Ethereum", "Polygon", "Sepolia", "EVM",
            "Smart Contracts", "dApps", "Hardhat", "OpenZeppelin",
            "Wallet Integration", "IPFS",
            "ERC-20", "ERC-721", "ERC-1155",
            "ERC-4337", "ERC-2771", "ERC-1967", "ERC-2612"
        ],
    },
    {
        category: "AI & ML",
        items: ["Finetuning", "Model Training", "Agentic AI", "Model serving", "Gemini API", "IBM WatsonX Granite", "REST APIs"],
    },
    {
        category: "DevOps",
        items: ["Docker", "Git", "CI/CD", "Coolify", "Vercel", "Render", "Netlify"],
    },
];

export const achievements = [
    {
        id: "polaris-fellowship-2026",
        title: "Polaris Fellowship 2026",
        description: "Shortlisted for Round 2 of the prestigious Polaris Fellowship 2026 — an elite residential program for the top 10 student builders in India.",
        icon: "🌌",
        url: "https://polariscampus.com",
    },
    {
        id: "age-of-agi-hackathon",
        title: "Age of AGI Hackathon — 1st Place",
        description: "Won 1st place with SandBench, a secure code benchmarking platform, AI model evaluation framework, and RL environment at Kalvium (Jun 12–14, 2026).",
        icon: "🏆",
        url: "https://sandbench.vercel.app/",
    },
    {
        id: "scaler-meta-hackathon",
        title: "Scaler x Meta Hackathon Finalist",
        description: "Built an AI/ML/RL training environment in a 48-hour hackathon hosted by Scaler, Meta, PyTorch, and Hugging Face.",
        icon: "🧠",
    },
    {
        id: "hackhub",
        title: "HackHub-25 Finalist",
        description: "VIT Chennai (36-hr hackathon)",
        icon: "🏆",
    },
    {
        id: "amarchain",
        title: "AmarChain Architect",
        description: "Web3 organ donation platform system design",
        icon: "🔗",
    },
    {
        id: "ibm-watson",
        title: "IBM TechXchange WatsonX Hackathon",
        description: "National participant (Generative AI for Productivity)",
        icon: "🤖",
    },
];
